djgg_shareprice_group:
    pattern:  /
    defaults: { _controller: "DjggSharepriceBundle:Group:grid" }

djgg_shareprice_group_grid:
    pattern:  /grid
    defaults: { _controller: "DjggSharepriceBundle:Group:grid" }

djgg_shareprice_group_show:
    pattern:  /{id}/show
    defaults: { _controller: "DjggSharepriceBundle:Group:show" }

djgg_shareprice_group_new:
    pattern:  /new
    defaults: { _controller: "DjggSharepriceBundle:Group:new" }

djgg_shareprice_group_create:
    pattern:  /create
    defaults: { _controller: "DjggSharepriceBundle:Group:create" }
    requirements: { _method: post }

djgg_shareprice_group_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DjggSharepriceBundle:Group:edit" }

djgg_shareprice_group_update:
    pattern:  /{id}/update
    defaults: { _controller: "DjggSharepriceBundle:Group:update" }
    requirements: { _method: post }

djgg_shareprice_group_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DjggSharepriceBundle:Group:delete" }
    requirements: { _method: post }
