djgg_shareprice_product:
    pattern:  /
    defaults: { _controller: "DjggSharepriceBundle:Product:grid" }

djgg_shareprice_product_grid:
    pattern:  /grid
    defaults: { _controller: "DjggSharepriceBundle:Product:grid" }

djgg_shareprice_product_show:
    pattern:  /{id}/show
    defaults: { _controller: "DjggSharepriceBundle:Product:show" }

djgg_shareprice_product_new:
    pattern:  /new
    defaults: { _controller: "DjggSharepriceBundle:Product:new" }

djgg_shareprice_product_create:
    pattern:  /create
    defaults: { _controller: "DjggSharepriceBundle:Product:create" }
    requirements: { _method: post }

djgg_shareprice_product_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DjggSharepriceBundle:Product:edit" }

djgg_shareprice_product_update:
    pattern:  /{id}/update
    defaults: { _controller: "DjggSharepriceBundle:Product:update" }
    requirements: { _method: post }

djgg_shareprice_product_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DjggSharepriceBundle:Product:delete" }
    requirements: { _method: post }
