djgg_shareprice_society:
    pattern:  /
    defaults: { _controller: "DjggSharepriceBundle:Society:grid" }

djgg_shareprice_society_grid:
    pattern:  /grid
    defaults: { _controller: "DjggSharepriceBundle:Society:grid" }

djgg_shareprice_society_show:
    pattern:  /{id}/show
    defaults: { _controller: "DjggSharepriceBundle:Society:show" }

djgg_shareprice_society_new:
    pattern:  /new
    defaults: { _controller: "DjggSharepriceBundle:Society:new" }

djgg_shareprice_society_create:
    pattern:  /create
    defaults: { _controller: "DjggSharepriceBundle:Society:create" }
    requirements: { _method: post }

djgg_shareprice_society_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DjggSharepriceBundle:Society:edit" }

djgg_shareprice_society_update:
    pattern:  /{id}/update
    defaults: { _controller: "DjggSharepriceBundle:Society:update" }
    requirements: { _method: post }

djgg_shareprice_society_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DjggSharepriceBundle:Society:delete" }
    requirements: { _method: post }
