#parameters:
#    dg_user.db.table_prefix: 

#services:
#    dg_user.tblprefix_subscriber:
#        class: Dg\UserBundle\Subscriber\TablePrefixSubscriber
#        arguments: [%dg_user.db.table_prefix%]
#        tags:
#            - { name: dg_user.doctrine.event_subscriber }
#    dg_eno1.example:
#        class: %dg_eno1.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
