<?php

namespace Djgg\SharepriceBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SocietyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocietyRepository extends EntityRepository
{
}
