parameters:
#    dg_tools.example.class: Dg\ToolsBundle\Example
    form.type.gmap_address.class: Dg\ToolsBundle\Form\Type\GMapAddressType
    
services:
#    dg_tools.example:
#        class: %dg_tools.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    form.type.gmap_address:
        class: %form.type.gmap_address.class%
        tags:
            -  { name: form.type, alias: gmap_address }
